import React, {
  useEffect, useMemo, useState,
} from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { getConfig } from '@edx/frontend-platform';
import { sendPageEvent, sendTrackEvent } from '@edx/frontend-platform/analytics';
import { getCountryList, getLocale, useIntl } from '@edx/frontend-platform/i18n';
import {
  Form, Icon, IconButton, Spinner, StatefulButton,
} from '@openedx/paragon';
import { Visibility, VisibilityOff } from '@openedx/paragon/icons';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import { Helmet } from 'react-helmet';
import Skeleton from 'react-loading-skeleton';
import { Link, useNavigate } from 'react-router-dom';

import ConfigurableRegistrationForm from './components/ConfigurableRegistrationForm';
import RegistrationFailure from './components/RegistrationFailure';
import {
  backupRegistrationForm,
  backupRegistrationFormBegin,
  clearRegistrationBackendError,
  registerNewUser,
  setEmailSuggestionInStore,
  setUserPipelineDataLoaded,
} from './data/actions';
import {
  FORM_SUBMISSION_ERROR,
  TPA_AUTHENTICATION_FAILURE,
} from './data/constants';
import getBackendValidations from './data/selectors';
import {
  isFormValid, prepareRegistrationPayload,
} from './data/utils';
import messages from './messages';
import {
  CountryField,
  EmailField,
  OrganizationCodeField,
  TermsOfService,
  UsernameField,
} from './RegistrationFields';
import {
  InstitutionLogistration,
  PasswordField,
  RedirectLogistration,
  ThirdPartyAuthAlert,
} from '../common-components';
import {
  clearThirdPartyAuthContextErrorMessage,
  getThirdPartyAuthContext as getRegistrationDataFromBackend,
} from '../common-components/data/actions';
import EnterpriseSSO from '../common-components/EnterpriseSSO';
import commonMessages from '../common-components/messages';
import ThirdPartyAuth from '../common-components/ThirdPartyAuth';
import {
  COMPLETE_STATE, LOGIN_PAGE, PENDING_STATE, REGISTER_PAGE,
} from '../data/constants';
import {
  getAllPossibleQueryParams,
  getTpaHint,
  getTpaProvider,
  isHostAvailableInQueryParams,
  setCookie,
  updatePathWithQueryParams,
} from '../data/utils';

/**
 * Main Registration Page component
 */
const RegistrationPage = (props) => {
  const { formatMessage } = useIntl();
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [isConfirmPasswordHidden, setIsConfirmPasswordHidden] = useState(true);

  const registrationEmbedded = isHostAvailableInQueryParams();
  const platformName = getConfig().SITE_NAME;
  const flags = {
    showConfigurableEdxFields: getConfig().SHOW_CONFIGURABLE_EDX_FIELDS,
    showConfigurableRegistrationFields: getConfig().ENABLE_DYNAMIC_REGISTRATION_FIELDS,
    showMarketingEmailOptInCheckbox: getConfig().MARKETING_EMAILS_OPT_IN,
    autoGeneratedUsernameEnabled: getConfig().ENABLE_AUTO_GENERATED_USERNAME,
  };
  const {
    handleInstitutionLogin,
    institutionLogin,
  } = props;

  const backedUpFormData = useSelector(state => state.register.registrationFormData);
  const registrationError = useSelector(state => state.register.registrationError);
  const registrationErrorCode = registrationError?.errorCode;
  const registrationResult = useSelector(state => state.register.registrationResult);
  const shouldBackupState = useSelector(state => state.register.shouldBackupState);
  const userPipelineDataLoaded = useSelector(state => state.register.userPipelineDataLoaded);
  const submitState = useSelector(state => state.register.submitState);

  const fieldDescriptions = useSelector(state => state.commonComponents.fieldDescriptions) || {};
  const optionalFields = useSelector(state => state.commonComponents.optionalFields) || {};
  const thirdPartyAuthApiStatus = useSelector(state => state.commonComponents.thirdPartyAuthApiStatus);
  const autoSubmitRegForm = useSelector(state => state.commonComponents.thirdPartyAuthContext.autoSubmitRegForm);
  const thirdPartyAuthErrorMessage = useSelector(state => state.commonComponents.thirdPartyAuthContext.errorMessage);
  const finishAuthUrl = useSelector(state => state.commonComponents.thirdPartyAuthContext.finishAuthUrl);
  const currentProvider = useSelector(state => state.commonComponents.thirdPartyAuthContext.currentProvider);
  const providers = useSelector(state => state.commonComponents.thirdPartyAuthContext.providers);
  const secondaryProviders = useSelector(state => state.commonComponents.thirdPartyAuthContext.secondaryProviders);
  const pipelineUserDetails = useSelector(state => state.commonComponents.thirdPartyAuthContext.pipelineUserDetails);

  const backendValidations = useSelector(getBackendValidations);
  const queryParams = useMemo(() => getAllPossibleQueryParams(), []);
  const tpaHint = useMemo(() => getTpaHint(), []);
  const countryList = useMemo(
    () => getCountryList(getLocale()).concat([{ code: 'US', name: 'United States' }]),
    [],
  );

  const [formFields, setFormFields] = useState({ ...backedUpFormData.formFields });
  const [configurableFormFields, setConfigurableFormFields] = useState({ ...backedUpFormData.configurableFormFields });
  const [errors, setErrors] = useState({ ...backedUpFormData.errors });
  const [errorCode, setErrorCode] = useState({ type: '', count: 0 });
  const [formStartTime, setFormStartTime] = useState(null);
  // temporary error state for embedded experience because we don't want to show errors on blur
  const [temporaryErrors, setTemporaryErrors] = useState({ ...backedUpFormData.errors });

  const registrationName = [
    configurableFormFields.first_name,
    configurableFormFields.last_name,
  ]
    .filter(value => typeof value === 'string' && value.trim())
    .map(value => value.trim())
    .join(' ') || formFields.name;

  const { cta, host } = queryParams;
  const buttonLabel = cta
    ? formatMessage(messages['create.account.cta.button'], { label: cta })
    : formatMessage(messages['create.account.for.free.button']);

  /**
   * Set the userPipelineDetails data in formFields for only first time
   */
  useEffect(() => {
    if (!userPipelineDataLoaded && thirdPartyAuthApiStatus === COMPLETE_STATE) {
      if (thirdPartyAuthErrorMessage) {
        setErrorCode(prevState => ({ type: TPA_AUTHENTICATION_FAILURE, count: prevState.count + 1 }));
      }
      if (pipelineUserDetails && Object.keys(pipelineUserDetails).length !== 0) {
        const { name = '', username = '', email = '' } = pipelineUserDetails;
        setFormFields(prevState => ({
          ...prevState, name, username, email,
        }));
        dispatch(setUserPipelineDataLoaded(true));
      }
    }
  }, [ // eslint-disable-line react-hooks/exhaustive-deps
    thirdPartyAuthApiStatus,
    thirdPartyAuthErrorMessage,
    pipelineUserDetails,
    userPipelineDataLoaded,
  ]);

  useEffect(() => {
    if (!formStartTime) {
      sendPageEvent('login_and_registration', 'register');
      const payload = { ...queryParams, is_register_page: true };
      if (tpaHint) {
        payload.tpa_hint = tpaHint;
      }
      dispatch(getRegistrationDataFromBackend(payload));
      setFormStartTime(Date.now());
    }
  }, [dispatch, formStartTime, queryParams, tpaHint]);

  /**
   * Backup the registration form in redux when register page is toggled.
   */
  useEffect(() => {
    if (shouldBackupState) {
      dispatch(backupRegistrationFormBegin({
        ...backedUpFormData,
        configurableFormFields: { ...configurableFormFields },
        formFields: { ...formFields },
        errors: { ...errors },
      }));
    }
  }, [shouldBackupState, configurableFormFields, formFields, errors, dispatch, backedUpFormData]);

  useEffect(() => {
    if (backendValidations) {
      if (registrationEmbedded) {
        setTemporaryErrors(prevErrors => ({ ...prevErrors, ...backendValidations }));
      } else {
        setErrors(prevErrors => ({ ...prevErrors, ...backendValidations }));
      }
    }
  }, [backendValidations, registrationEmbedded]);

  useEffect(() => {
    const hasBackendFieldErrors = backendValidations
      && Object.keys(backendValidations).length > 0;

    if (registrationErrorCode && !hasBackendFieldErrors) {
      setErrorCode(prevState => ({ type: registrationErrorCode, count: prevState.count + 1 }));
    }
  }, [registrationErrorCode, backendValidations]);

  useEffect(() => {
    if (registrationResult.success) {
      // This event is used by GTM
      sendTrackEvent('edx.bi.user.account.registered.client', {});

      // This is used by the "User Retention Rate Event" on GTM
      setCookie(getConfig().USER_RETENTION_COOKIE_NAME, true);
    }
  }, [registrationResult]);

  const goToLogin = (event) => {
    event.preventDefault();
    sendTrackEvent('edx.bi.login_form.toggled', { category: 'user-engagement' });
    dispatch(clearThirdPartyAuthContextErrorMessage());
    dispatch(backupRegistrationForm());
    navigate(updatePathWithQueryParams(LOGIN_PAGE));
  };

  const handleOnChange = (event) => {
    const { name } = event.target;
    const value = event.target.type === 'checkbox' ? event.target.checked : event.target.value;
    if (registrationError[name]) {
      dispatch(clearRegistrationBackendError(name));
    }
    setErrors(prevErrors => ({ ...prevErrors, [name]: '' }));
    setFormFields(prevState => ({ ...prevState, [name]: value }));
  };

  const handleCountryChange = (event, countryValue) => {
    const { name } = event.target;

    if (registrationError[name]) {
      dispatch(clearRegistrationBackendError(name));
    }

    setErrors(prevErrors => ({ ...prevErrors, [name]: '' }));
    setConfigurableFormFields(prevState => ({
      ...prevState,
      [name]: { ...countryValue },
    }));
  };

  const handleErrorChange = (fieldName, error) => {
    if (registrationEmbedded) {
      setTemporaryErrors(prevErrors => ({
        ...prevErrors,
        [fieldName]: error,
      }));
      if (error === '' && errors[fieldName] !== '') {
        setErrors(prevErrors => ({
          ...prevErrors,
          [fieldName]: error,
        }));
      }
    } else {
      setErrors(prevErrors => ({
        ...prevErrors,
        [fieldName]: error,
      }));
    }
  };

  const handleCountryFocus = () => {
    handleErrorChange('country', '');
  };

  const registerUser = () => {
    const totalRegistrationTime = (Date.now() - formStartTime) / 1000;
    let payload = { ...formFields };
    payload.name = registrationName;

    if (currentProvider) {
      delete payload.password;
      delete payload.confirm_password;
      payload.social_auth_provider = currentProvider;
    }
    if (flags.autoGeneratedUsernameEnabled) {
      delete payload.username;
    }

    // Validating form data before submitting
    const { isValid, fieldErrors, emailSuggestion } = isFormValid(
      payload,
      registrationEmbedded ? temporaryErrors : errors,
      configurableFormFields,
      fieldDescriptions,
      formatMessage,
    );
    setErrors({ ...fieldErrors });
    dispatch(setEmailSuggestionInStore(emailSuggestion));

    // returning if not valid
    if (!isValid) {
      setErrorCode(prevState => ({ type: FORM_SUBMISSION_ERROR, count: prevState.count + 1 }));
      return;
    }

    // Preparing payload for submission
    payload = prepareRegistrationPayload(
      payload,
      configurableFormFields,
      flags.showMarketingEmailOptInCheckbox,
      totalRegistrationTime,
      queryParams);

    // making register call
    dispatch(registerNewUser(payload));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    registerUser();
  };

  useEffect(() => {
    if (autoSubmitRegForm && userPipelineDataLoaded) {
      registerUser();
    }
  }, [autoSubmitRegForm, userPipelineDataLoaded]); // eslint-disable-line react-hooks/exhaustive-deps

  // Progressive profiling needs a logged-in user. CBA registration returns
  // authenticated_user: null until email is activated — show the notice instead.
  const hasAuthenticatedUser = Boolean(
    registrationResult.authenticatedUser
    && (registrationResult.authenticatedUser.userId
      || registrationResult.authenticatedUser.username),
  );

  const redirectToProgressiveProfilingPage = (
    getConfig().ENABLE_PROGRESSIVE_PROFILING_ON_AUTHN
    && !!Object.keys(optionalFields.fields || {}).length
    && hasAuthenticatedUser
  );

  const previewActivationNotice = (
    process.env.NODE_ENV === 'development'
    && (queryParams.preview_activation === '1' || queryParams.preview_activation === 'true')
  );

  const showActivationNotice = (
    previewActivationNotice
    || (
      registrationResult.success
      && !currentProvider
      && !registrationEmbedded
      && !redirectToProgressiveProfilingPage
    )
  );

  const renderForm = () => {
    if (institutionLogin) {
      return (
        <InstitutionLogistration
          secondaryProviders={secondaryProviders}
          headingTitle={formatMessage(messages['register.institution.login.page.title'])}
        />
      );
    }
    return (
      <>
        <Helmet>
          <title>{formatMessage(messages['register.page.title'], { siteName: getConfig().SITE_NAME })}</title>
        </Helmet>
        {!showActivationNotice && (
          <RedirectLogistration
            host={host}
            authenticatedUser={registrationResult.authenticatedUser}
            success={registrationResult.success}
            redirectUrl={registrationResult.redirectUrl}
            finishAuthUrl={finishAuthUrl}
            optionalFields={optionalFields}
            registrationEmbedded={registrationEmbedded}
            redirectToProgressiveProfilingPage={redirectToProgressiveProfilingPage}
          />
        )}
        {showActivationNotice && (
          <div
            id="registration-activation-notice"
            className="cba-auth-card cba-auth-card--notice"
            role="status"
          >
            <header className="cba-auth-card__header">
              <p className="cba-auth-card__eyebrow">
                {formatMessage(messages['registration.activation.eyebrow'])}
              </p>
              <h2 className="cba-auth-card__title">
                {formatMessage(messages['registration.activation.heading'])}
              </h2>
              <p className="cba-auth-card__lead">
                {formatMessage(messages['registration.activation.lead'])}
              </p>
              <p className="cba-auth-card__lead">
                {formatMessage(messages['registration.activation.note'])}
              </p>
            </header>
            <p className="cba-auth-card__footer mb-0">
              <Link
                className="cba-auth-notice__cta"
                to={updatePathWithQueryParams(LOGIN_PAGE)}
              >
                {formatMessage(messages['registration.activation.sign.in'])}
              </Link>
            </p>
          </div>
        )}
        {!showActivationNotice && autoSubmitRegForm && !errorCode.type && (
          <div className="cba-auth-card cba-auth-card--notice text-center">
            <Spinner animation="border" variant="primary" id="tpa-spinner" />
          </div>
        )}
        {!showActivationNotice && !(autoSubmitRegForm && !errorCode.type) && (
          <div
            className={classNames(
              'cba-auth-register',
              { 'w-100 m-auto pt-4 main-content': registrationEmbedded },
            )}
          >
            <div className="cba-auth-card cba-auth-card--register">
              <header className="cba-auth-card__header">
                <p className="cba-auth-card__eyebrow">
                  {formatMessage(messages['registration.page.eyebrow'])}
                </p>
                <h1 className="cba-auth-card__title">
                  {formatMessage(messages['registration.page.heading'])}
                </h1>
                <p className="cba-auth-card__lead">
                  {formatMessage(messages['registration.page.subheading'], { siteName: platformName })}
                </p>
              </header>
              <ThirdPartyAuthAlert
                currentProvider={currentProvider}
                platformName={platformName}
                referrer={REGISTER_PAGE}
              />
              <RegistrationFailure
                errorCode={errorCode.type}
                failureCount={errorCode.count}
                context={{ provider: currentProvider, errorMessage: thirdPartyAuthErrorMessage }}
              />
              <Form id="registration-form" name="registration-form">

                <ConfigurableRegistrationForm
                  email={formFields.email}
                  fieldErrors={errors}
                  formFields={configurableFormFields}
                  setFieldErrors={registrationEmbedded ? setTemporaryErrors : setErrors}
                  setFormFields={setConfigurableFormFields}
                  autoSubmitRegistrationForm={autoSubmitRegForm}
                  fieldDescriptions={fieldDescriptions}
                  optionalFields={optionalFields}
                  renderCountryField={false}
                />

                <EmailField
                  name="email"
                  type="email"
                  value={formFields.email}
                  confirmEmailValue={configurableFormFields?.confirm_email}
                  handleErrorChange={handleErrorChange}
                  handleChange={handleOnChange}
                  errorMessage={errors.email}
                  autoComplete="email"
                  helpText={[formatMessage(messages['help.text.email'])]}
                  floatingLabel={formatMessage(messages['registration.email.label'])}
                />

                {!flags.autoGeneratedUsernameEnabled && (
                  <UsernameField
                    name="username"
                    spellCheck="false"
                    autoComplete="nickname"
                    value={formFields.username}
                    handleChange={handleOnChange}
                    handleErrorChange={handleErrorChange}
                    errorMessage={errors.username}
                    helpText={[formatMessage(messages['help.text.username.1']), formatMessage(messages['help.text.username.2'])]}
                    floatingLabel={formatMessage(messages['registration.username.label'])}
                  />
                )}

                <OrganizationCodeField
                  name="organization_code"
                  value={formFields.organization_code || ''}
                  handleChange={handleOnChange}
                  handleErrorChange={handleErrorChange}
                  errorMessage={errors.organization_code}
                  helpText={[
                    formatMessage(messages['help.text.organization.code']),
                  ]}
                  floatingLabel={formatMessage(
                    messages['registration.organization.code.label'],
                  )}
                />

                <CountryField
                  countryList={countryList}
                  selectedCountry={configurableFormFields.country || {
                    countryCode: '',
                    displayValue: '',
                  }}
                  errorMessage={errors.country || ''}
                  onChangeHandler={handleCountryChange}
                  handleErrorChange={handleErrorChange}
                  onFocusHandler={handleCountryFocus}
                  isRequired={Object.prototype.hasOwnProperty.call(fieldDescriptions, 'country')}
                />
                {!currentProvider && (
                  <>
                    <PasswordField
                      name="password"
                      value={formFields.password}
                      autoComplete="new-password"
                      handleChange={handleOnChange}
                      handleErrorChange={handleErrorChange}
                      errorMessage={errors.password}
                      floatingLabel={formatMessage(messages['registration.password.label'])}
                      nameValue={registrationName}
                      emailValue={formFields.email}
                      usernameValue={formFields.username}
                      organizationCode={formFields.organization_code || ''}
                    />

                    <Form.Group
                      controlId="confirm_password"
                      isInvalid={Boolean(errors.confirm_password)}
                    >
                      <Form.Control
                        as="input"
                        className="form-group__form-field"
                        type={isConfirmPasswordHidden ? 'password' : 'text'}
                        name="confirm_password"
                        value={formFields.confirm_password || ''}
                        autoComplete="new-password"
                        aria-invalid={Boolean(errors.confirm_password)}
                        onChange={handleOnChange}
                        trailingElement={(
                          <IconButton
                            name="confirmPasswordIcon"
                            src={isConfirmPasswordHidden ? Visibility : VisibilityOff}
                            iconAs={Icon}
                            onClick={() => setIsConfirmPasswordHidden(value => !value)}
                            size="sm"
                            variant="secondary"
                            alt={formatMessage(
                              commonMessages[isConfirmPasswordHidden ? 'show.password' : 'hide.password'],
                            )}
                          />
                        )}
                        floatingLabel={formatMessage(
                          messages['registration.confirm.password.label'],
                        )}
                      />
                      {errors.confirm_password && (
                        <Form.Control.Feedback
                          className="form-text-size"
                          hasIcon={false}
                          feedback-for="confirm_password"
                          type="invalid"
                        >
                          {errors.confirm_password}
                        </Form.Control.Feedback>
                      )}
                    </Form.Group>
                  </>
                )}

                {Object.prototype.hasOwnProperty.call(fieldDescriptions, 'terms_of_service') && (
                  <TermsOfService
                    value={configurableFormFields.terms_of_service}
                    onChangeHandler={(event) => {
                      setConfigurableFormFields(prevState => ({
                        ...prevState,
                        terms_of_service: event.target.checked,
                      }));
                      setErrors(prevErrors => ({
                        ...prevErrors,
                        terms_of_service: '',
                      }));
                    }}
                    errorMessage={errors.terms_of_service}
                  />
                )}

                <StatefulButton
                  id="register-user"
                  name="register-user"
                  type="submit"
                  variant="brand"
                  className="register-button mt-4 mb-4"
                  state={submitState}
                  labels={{
                    default: buttonLabel,
                    pending: '',
                  }}
                  onClick={handleSubmit}
                  onMouseDown={(e) => e.preventDefault()}
                />
                {!registrationEmbedded && (
                  <>
                    <div className="cba-auth-card__footer">
                      <span>
                        {formatMessage(messages['registration.already.have.account'])}
                        {' '}
                      </span>
                      <Link
                        id="login-account"
                        name="login-account"
                        to={updatePathWithQueryParams(LOGIN_PAGE)}
                        onClick={goToLogin}
                      >
                        {formatMessage(commonMessages['logistration.sign.in'])}
                      </Link>
                    </div>
                    <ThirdPartyAuth
                      currentProvider={currentProvider}
                      providers={providers}
                      secondaryProviders={secondaryProviders}
                      handleInstitutionLogin={handleInstitutionLogin}
                      thirdPartyAuthApiStatus={thirdPartyAuthApiStatus}
                    />
                  </>
                )}
              </Form>
            </div>
          </div>
        )}

      </>
    );
  };

  if (tpaHint) {
    if (thirdPartyAuthApiStatus === PENDING_STATE) {
      return <Skeleton height={36} />;
    }
    const { provider, skipHintedLogin } = getTpaProvider(tpaHint, providers, secondaryProviders);
    if (skipHintedLogin) {
      window.location.href = getConfig().LMS_BASE_URL + provider.registerUrl;
      return null;
    }
    return provider ? <EnterpriseSSO provider={provider} /> : renderForm();
  }
  return (
    renderForm()
  );
};

RegistrationPage.propTypes = {
  institutionLogin: PropTypes.bool,
  // Actions
  handleInstitutionLogin: PropTypes.func,
};

RegistrationPage.defaultProps = {
  handleInstitutionLogin: null,
  institutionLogin: false,
};

export default RegistrationPage;
